### ISSUE TITLE
ERR_INVALID_COUNTRY

### ISSUE THREAD

**Issue by umairakram500** [yamdraco/lalamove-php#7]
Hi mate, I have tried to integrate this repo but it's not giving me any response. I have the credentials of Thailand. I also try to Direct API but when the response is ERR_INVALID_COUNTRY. 
Please help me, I have spent approx 2 weeks to solve it. 
I will be very thankful to you.

**Comment by umairakram500** [comment]
I tried to get quotation by using this repo or direct API but repo implementation no any response and direct API Invalid country error. They send me POSTMAN and it's working in it but when I try to implement the same process, API responds to me a country error. I had tried to solve it with the help of support but support does also not have any reasonable response.

**Comment by umairakram500** [comment]
According to my observation, there is problem in signature generation. Postman signature and PHP signature is different. The signature generation process is the same as you but i couldn't understand why this problem is occurred.

**Comment by yamdraco** [comment]
Hi @umairakram500, it is best to go through with Lalamove instead as this repo is a proxy to the Lalamove API. As far as I understand base on user's feedback the way the signature generated from the repo should be correct. Do you mind getting the HTTP status code that comes back from the call using this repo. I should be able to help you out. May I also know which country you are calling the order to (and city as well)

**Comment by umairakram500** [comment]
Hi @yamdraco, Thank you very much for the response. 
We have tried both method Your Repo and Direct API. When we use your repo its no response and when try Direct API ERR_INVALID_COUNTRY. We have followed each and everything but not understands what is the problem. [Here](https://drive.google.com/open?id=1QhhUg4-TEbEA4e_26N-IElWmxlcyVnF8) is my code for implementation of Lalamove API. Please suggest to us where we are making a problem. I will be very thankful to you.

**Comment by yamdraco** [comment]
Can I ask if the key and secret you have is also from SG?

**Comment by umairakram500** [comment]
@yamdraco No the key and Secret I have is from Thailand

**Comment by yamdraco** [comment]
hi @umairakram500 that's easy to know why then, the body you are saying is SG and the order you are trying to do is in thailand. So change the body to thailand related data.
